

# This is a basic workflow to help you get started with Actions

name: Publish LeoSurvey Frontend and Backend

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: ['main']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_backend:
    name: Build backend
    runs-on: ubuntu-latest 
    env:
      IMAGE_NAME: leosurvey-backend 
    defaults:
      run:
        working-directory: ./LeoSurvey
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Package
        run: mvn package -DskipTests
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }} 
      - name: Build image
        run: docker build . -f src/main/docker/Dockerfile.jvm --tag $IMAGE_NAME 
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') 
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION 
  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: leosurvey-frontend
    defaults:
      run:
        working-directory: ./Angular/leo-survey
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build image
        run: docker build . --tag $IMAGE_NAME
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

